baseURL = "https://ibnuhamzah404.github.io/programerbucin.github.io/"
languageCode = "en-us"
title = "Peogramer Bucin"
theme = "programerbucin"
paginate = 2
[params]
    Description = "tempat belajar koding asik"