baseURL = "https://ibnuhamzah404.github.io/programerbucin.github.io/public/"
languageCode = "en-us"
title = "Peogramer Bucin"
theme = "blog-v1"
paginate = 2
[params]
    Description = "tempat belajar koding asik"